server:
  port: 8080

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: pku
    password: pku
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never

